### ISSUE TITLE
Chrome dev tools no longer pauses stack frames for iframe code

### ISSUE THREAD

**Issue by samreid** [phetsims/assert#3]
Google chrome dev tools used to pause with a navigable stack frame for iframe assertion failures.  However, in the last few months, it instead prints the iframe stack trace to the console instead, and you cannot access any of the stack frames or variable values.  To work around this, I have been temporarily adding `debugger` to assert.js, but this feels hackish.  I wonder if we should (a) find out how to get chrome to pause stack frames again in iframes or (b) add code to assert.js that basically says:

```js
      console && console.log && console.log( 'Assertion failed: ' + message );
      if (isInIFrameCode()){
        debugger;
      }
      throw new Error( 'Assertion failed: ' + message );
```

**Comment by zepumph** [comment]
This would be nice!

**Comment by jonathanolson** [comment]
(a) desired but (b) sounds fine (will need comment to disable lint for the no-debugger rule).

**Comment by jessegreenberg** [comment]
This StackOverflow thread might be helpful, but I haven't tested it myself:

http://stackoverflow.com/questions/3275816/debugging-iframes-with-chrome-developer-tools

**Comment by jessegreenberg** [comment]
@samreid gave it a test, but initially noticed that it might be flaky.  He will test it again, but if it doesn't work out we are all OK with modifying assert as mentioned in https://github.com/phetsims/assert/issues/3#issue-199738019.

**Comment by samreid** [comment]
Testing it seems like I am now getting breakpoints in Chrome Dev Tools (even after selecting "top" again in the stack frames.)  I'll investigate this further before committing to assert.js.

**Comment by pixelzoom** [comment]
If modifying assert.js, please reference this issue in the code.

**Comment by samreid** [comment]
Unassigning until this problem comes up again for me.

**Comment by pixelzoom** [comment]
@samreid is this still an issue? Can it be closed?

**Comment by samreid** [comment]
The Chrome Dev tools setting "Pause on exceptions" seems to have the correct behavior.  I think this issue can be closed but want to run it past @zepumph to double check.

**Comment by zepumph** [comment]
I agree it seems like it has fixed itself, it has been quite some time since I had to add "debugger" into assert in order to get it to pause on an exception. Much of that may be attributed to the better error handling we have in wrappers now. All of the wrapper suite wrappers throw the errors caught from the sim side now too. Closing
