### ISSUE TITLE
Update the assert error to handle a lack of message

### ISSUE THREAD

**Issue by zepumph** [phetsims/assert#4]
From dev meeting today. We don't require that assertion messages are included in every assert call. Therefore it would be nice if the error message handled this case without saying: `Assertion failed: undefined`.

@jonathanolson had the recommendation to try to add the lineNum/file that the assert came from, otherwise we can just say `Assertion failed` or something.

**Comment by phet-steele** [comment]
> @jonathanolson had the recommendation to try to add the lineNum/file that the assert came from,

Actually he recommended the ***code*** from the line the assertion is on. Assertions already reveal the line number and file in the stack trace. It would look something like:

`Assertion failed: !this.isFilledProperty.value && !this.appearsFilledProperty.value && !this.targetedPiece`

**Comment by zepumph** [comment]
Ahhh you're correct @phet-steele, thanks for that. I wasn't able to find any way to easily accomplish the aforementioned feature. The best I found was using `arguments.callee` to parse the parameter name within the functon (for the assert function "predicate" and "message"), which isn't helpful. Also this feature wasn't available in `strict` mode, so I think that is a dead end. @jonathanolson did you have any other thoughts about methods before I settle on a simple conditional to remove the ": undefined" to look a bit more crisp?

**Comment by jonathanolson** [comment]
`arguments.callee.toString()` gets the function content, but `try { throw new Error(); } catch ( e ) { e.stack; }` only gives the line offset to within the file, not the function. I don't see a good way of getting the offset to the exact line synchronously.

So, I believe this issue should be closed.

@phet-steele, a similar enhancement could, however, be made to bayes continuous testing. Given the stack information of the error (including line/column offsets), it could look up the line and display more information in bayes reports. Make an issue for that if desired?

**Comment by zepumph** [comment]
@phet-steele, all is done here, please make a new issue if desired, and close this issue when ready.

**Comment by phet-steele** [comment]
> @phet-steele, a similar enhancement could, however, be made to bayes continuous testing. Given the stack information of the error (including line/column offsets), it could look up the line and display more information in bayes reports.

No need, a human can look that up super easily.
