### ISSUE TITLE
Use console.error instead of console.log

### ISSUE THREAD

**Issue by samreid** [phetsims/assert#8]
In https://github.com/phetsims/phet-io-wrappers/issues/506#issuecomment-1561656667 @zepumph said:

> Perhaps assert should console.error instead of console.log

I agree we should use console.error instead of console.log.  Here's a picture of a test assertion with assert the way it is now:

![image](https://github.com/phetsims/assert/assets/679486/a7299b45-be72-4b49-bcb5-45d3ba274214)

Using console.error, it looks like this:

![image](https://github.com/phetsims/assert/assets/679486/bbd13544-73c4-49b8-82ad-0dfda9e340c0)

And you can pop open the triangle like so:

![image](https://github.com/phetsims/assert/assets/679486/406fdfd5-69b2-4a24-a602-aa081ad08031)

@zepumph or @jonathanolson ok to commit this change?  Or should we check in at dev meeting today?

**Comment by samreid** [comment]
Will this create complication for any of our tooling that processes errors across different sim versions?

**Comment by zepumph** [comment]
I think this makes sense and would be valuable. I think that the red highlighting would only be an improvement, and we, as developers, are already quite trained to look at the "first red" in the console when a problem occurs.

**Comment by chrisklus** [comment]
From 5/25/23 dev meeting: We like it! Thanks!

**Comment by zepumph** [comment]
Awesome. Thanks team.
