### ISSUE TITLE
Increase the stack trace limit

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/assert#9]
@samreid and I were tracking down a CT error and found that the default stack trace limit of 10 was making it difficult to find the root cause of certain issues (see screenshot). We are proposing to increase the stack trace limit for Errors created in `assert` from the default of 10 to something higher, like 30.

![Screen Shot 2024-05-14 at 12 46 01 PM](https://github.com/phetsims/assert/assets/108756567/5826b256-c55d-454f-b740-a8d812e20b48)

**Comment by zepumph** [comment]
pull request complete. Closing
